# Generated by Django 4.2 on 2023-04-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CTG', 'Category'), ('TAG', 'tag')], max_length=3)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'clothing_tag',
            },
        ),
    ]
